In [ ]:
import pymongo

In [ ]:
# stringa di connessione 3.4 recuperata da Atlas https://www.mongodb.com/cloud/atlas/register
client = pymongo.MongoClient(
    "mongodb://webUser:xxx123xxx@cluster0-shard-00-00.algwo.mongodb.net:27017,cluster0-shard-00-01.algwo.mongodb.net:27017,cluster0-shard-00-02.algwo.mongodb.net:27017/?ssl=true&replicaSet=atlas-am4cb3-shard-0&authSource=admin&retryWrites=true&w=majority")
db = client.sample_airbnb # nome del database

In [ ]:
import pandas as pd

In [ ]:
doc = db.listingsAndReviews.find_one()
doc

{'_id': '10006546',
 'access': 'We are always available to help guests. The house is fully available to guests. We are always ready to assist guests. when possible we pick the guests at the airport.  This service transfer have a cost per person. We will also have service "meal at home" with a diverse menu and the taste of each. Enjoy the moment!',
 'accommodates': 8,
 'address': {'country': 'Portugal',
  'country_code': 'PT',
  'government_area': 'Cedofeita, Ildefonso, Sé, Miragaia, Nicolau, Vitória',
  'location': {'coordinates': [-8.61308, 41.1413],
   'is_location_exact': False,
   'type': 'Point'},
  'market': 'Porto',
  'street': 'Porto, Porto, Portugal',
  'suburb': ''},
 'amenities': ['TV',
  'Cable TV',
  'Wifi',
  'Kitchen',
  'Paid parking off premises',
  'Smoking allowed',
  'Pets allowed',
  'Buzzer/wireless intercom',
  'Heating',
  'Family/kid friendly',
  'Washer',
  'First aid kit',
  'Fire extinguisher',
  'Essentials',
  'Hangers',
  'Hair dryer',
  'Iron',
  'Pack ’n Play/travel crib',
  'Room-darkening shades',
  'Hot water',
  'Bed linens',
  'Extra pillows and blankets',
  'Microwave',
  'Coffee maker',
  'Refrigerator',
  'Dishwasher',
  'Dishes and silverware',
  'Cooking basics',
  'Oven',
  'Stove',
  'Cleaning before checkout',
  'Waterfront'],
 'availability': {'availability_30': 28,
  'availability_365': 239,
  'availability_60': 47,
  'availability_90': 74},
 'bathrooms': Decimal128('1.0'),
 'bed_type': 'Real Bed',
 'bedrooms': 3,
 'beds': 5,
 'calendar_last_scraped': datetime.datetime(2019, 2, 16, 5, 0),
 'cancellation_policy': 'moderate',
 'cleaning_fee': Decimal128('35.00'),
 'description': 'Fantastic duplex apartment with three bedrooms, located in the historic area of Porto, Ribeira (Cube) - UNESCO World Heritage Site. Centenary building fully rehabilitated, without losing their original character. Privileged views of the Douro River and Ribeira square, our apartment offers the perfect conditions to discover the history and the charm of Porto. Apartment comfortable, charming, romantic and cozy in the heart of Ribeira. Within walking distance of all the most emblematic places of the city of Porto. The apartment is fully equipped to host 8 people, with cooker, oven, washing machine, dishwasher, microwave, coffee machine (Nespresso) and kettle. The apartment is located in a very typical area of the city that allows to cross with the most picturesque population of the city, welcoming, genuine and happy people that fills the streets with his outspoken speech and contagious with your sincere generosity, wrapped in a only parochial spirit. We are always available to help guests',
 'extra_people': Decimal128('15.00'),
 'first_review': datetime.datetime(2016, 1, 3, 5, 0),
 'guests_included': Decimal128('6'),
 'host': {'host_about': 'Gostamos de passear, de viajar, de conhecer pessoas e locais novos, gostamos de desporto e animais! Vivemos na cidade mais linda do mundo!!!',
  'host_has_profile_pic': True,
  'host_id': '51399391',
  'host_identity_verified': True,
  'host_is_superhost': False,
  'host_listings_count': 3,
  'host_location': 'Porto, Porto District, Portugal',
  'host_name': 'Ana&Gonçalo',
  'host_neighbourhood': '',
  'host_picture_url': 'https://a0.muscache.com/im/pictures/fab79f25-2e10-4f0f-9711-663cb69dc7d8.jpg?aki_policy=profile_x_medium',
  'host_response_rate': 100,
  'host_response_time': 'within an hour',
  'host_thumbnail_url': 'https://a0.muscache.com/im/pictures/fab79f25-2e10-4f0f-9711-663cb69dc7d8.jpg?aki_policy=profile_small',
  'host_total_listings_count': 3,
  'host_url': 'https://www.airbnb.com/users/show/51399391',
  'host_verifications': ['email',
   'phone',
   'reviews',
   'jumio',
   'offline_government_id',
   'government_id']},
 'house_rules': 'Make the house your home...',
 'images': {'medium_url': '',
  'picture_url': 'https://a0.muscache.com/im/pictures/e83e702f-ef49-40fb-8fa0-6512d7e26e9b.jpg?aki_policy=large',
  'thumbnail_url': '',
  'xl_picture_url': ''},
 'interaction': 'Cot - 10 € / night Dog - € 7,5 / night',
 'last_review': datetime.datetime(2019, 1, 20, 5, 0),
 'last_scraped': datetime.datetime(2019, 2, 16, 5, 0),
 'listing_url': 'https://www.airbnb.com/rooms/10006546',
 'maximum_nights': '30',
 'minimum_nights': '2',
 'name': 'Ribeira Charming Duplex',
 'neighborhood_overview': "In the neighborhood of the river, you can find several restaurants as varied flavors, but without forgetting the so traditional northern food. You can also find several bars and pubs to unwind after a day's visit to the magnificent Port. To enjoy the Douro River can board the boats that daily make the ride of six bridges. You can also embark towards Régua, Barca d'Alva, Pinhão, etc and enjoy the Douro Wine Region, World Heritage of Humanity. The Infante's house is a few meters and no doubt it deserves a visit. They abound grocery stores, bakeries, etc. to make your meals. Souvenir shop, wine cellars, etc. to bring some souvenirs.",
 'notes': 'Lose yourself in the narrow streets and staircases zone, have lunch in pubs and typical restaurants, and find the renovated cafes and shops in town. If you like exercise, rent a bicycle in the area and ride along the river to the sea, where it will enter beautiful beaches and terraces for everyone. The area is safe, find the bus stops 1min and metro line 5min. The bustling nightlife is a 10 min walk, where the streets are filled with people and entertainment for all. But Porto is much more than the historical center, here is modern museums, concert halls, clean and cared for beaches and surf all year round. Walk through the Ponte D. Luis and visit the different Caves of Port wine, where you will enjoy the famous port wine. Porto is a spoken city everywhere in the world as the best to be visited and savored by all ... natural beauty, culture, tradition, river, sea, beach, single people, typical food, and we are among those who best receive tourists, confirm! Come visit us and feel at ho',
 'number_of_reviews': 51,
 'price': Decimal128('80.00'),
 'property_type': 'House',
 'review_scores': {'review_scores_accuracy': 9,
  'review_scores_checkin': 10,
  'review_scores_cleanliness': 9,
  'review_scores_communication': 10,
  'review_scores_location': 10,
  'review_scores_rating': 89,
  'review_scores_value': 9},
 'reviews': [{'_id': '58663741',
   'comments': 'A casa da Ana e do Gonçalo foram o local escolhido para a passagem de ano com um grupo de amigos. Fomos super bem recebidos com uma grande simpatia e predisposição a ajudar com qualquer coisa que fosse necessário.\r\nA casa era ainda melhor do que parecia nas fotos, totalmente equipada, com mantas, aquecedor e tudo o que pudessemos precisar.\r\nA localização não podia ser melhor! Não há melhor do que acordar de manhã e ao virar da esquina estar a ribeira do Porto.',
   'date': datetime.datetime(2016, 1, 3, 5, 0),
   'listing_id': '10006546',
   'reviewer_id': '51483096',
   'reviewer_name': 'Cátia'},
  {'_id': '62413197',
   'comments': "We are french's students, we traveled some days in Porto, this space was good and we can cooking easly. It was rainning so we eard every time the water fall to the ground in the street when we sleeping. But It was cool and or was well received by Ana et Gonçalo",
   'date': datetime.datetime(2016, 2, 14, 5, 0),
   'listing_id': '10006546',
   'reviewer_id': '40031996',
   'reviewer_name': 'Théo'},
  {'_id': '68310569',
   'comments': "We had a spledid time in the old centre of Porto.\r\nThe appartment is very well situated next to the old Ribeira square. It's perfect to have such an appartment to your disposal, you feel home, and have a place to relax between the exploration of this very nice city.\r\nWe thank Ana & Gonçalo, and we hope the appartment is free when we go back next year. Porto is charming original.",
   'date': datetime.datetime(2016, 4, 4, 4, 0),
   'listing_id': '10006546',
   'reviewer_id': '53859850',
   'reviewer_name': 'Bart'},
  {'_id': '69693942',
   'comments': "Ana and Goncalo were very helpful and accommodating. When they were not available they put us in touch with their nephew who was equally as helpful. The flat was as described, neat and tidy. The weather was quite cold, but thankfully A&G left us with extra blankets and electric heaters to use. Location was great. Outside the flat there was a slight smell of the river/ sewage, but in all honesty it did not come into the flat, and once you go down the road it doesn't carry on. This may also have been down to the very wet weather we had while there. All in all, very happy and would definitely recommend.",
   'date': datetime.datetime(2016, 4, 12, 4, 0),
   'listing_id': '10006546',
   'reviewer_id': '3135623',
   'reviewer_name': 'Alex'},
  {'_id': '71451096',
   'comments': "The hosts were very accommodating and agreed to meet with my parents as they were arriving before us. Communicated very well and always responded in a very timely manner. You couldn't have asked for a better location of this apartment and the place was identical to the pictures in the in the listing.",
   'date': datetime.datetime(2016, 4, 25, 4, 0),
   'listing_id': '10006546',
   'reviewer_id': '13187858',
   'reviewer_name': 'Dan'},
  {'_id': '73191268',
   'comments': "THE PLACE TO BE, l'appartement est situé au milieu de la Ribeira , tout peut se faire à pieds c'est l'ideal,l'appartement est très bien agencé et équipé.\r\nNous avons passé un séjour très agréable dans ce duplex avec beaucoup de charme .\r\nAccueil très chaleureux de Ana et Gonçalo, ils ont pris du temps pour nous indiquer tout ce qu'il y avait à faire sur Porto et répondus  à toutes nos interrogations en terme de commodités.. Merci..\r\n",
   'date': datetime.datetime(2016, 5, 7, 4, 0),
   'listing_id': '10006546',
   'reviewer_id': '61434690',
   'reviewer_name': 'Anne'},
  {'_id': '77438107',
   'comments': 'We had a great time in Porto. Ana’s & Goncalo’s apartment is located right in the heart of the Old Town and is great value for money. You really are at the centre of things and it’s the perfect place to get swept away in the hustle and bustle of Porto. Ana and Goncalo were great hosts.',
   'date': datetime.datetime(2016, 5, 31, 4, 0),
   'listing_id': '10006546',
   'reviewer_id': '3673216',
   'reviewer_name': 'Chris'},
  {'_id': '89637734',
   'comments': "Ana and Gonçalo were very welcoming and made a lot of information about Porto's sights available. It was very clean, very beautiful and the location was superb. It does have a lot of restaurants around it, so it could be a bit noisy for us at night but otherwise  great location. We would stay there again. ",
   'date': datetime.datetime(2016, 7, 29, 4, 0),
   'listing_id': '10006546',
   'reviewer_id': '9172374',
   'reviewer_name': 'Leslie'},
  {'_id': '96574146',
   'comments': "Super appartement très bien placé, au cœur de l'animation de la Ribeira !\r\nNous avons passé un super séjour à Porto !\r\nToutes les informations données par Ana et les documents laissés nous ont bien aidé à organiser notre séjour.  Nous avons (presque) tout fait à pied ! Le parking Ribeira est proche et bien utile pour garer le véhicule.\r\nMerci !!!\r\nPhilippe\r\n",
   'date': datetime.datetime(2016, 8, 23, 4, 0),
   'listing_id': '10006546',
   'reviewer_id': '71985274',
   'reviewer_name': 'Philippe'},
  {'_id': '108444999',
   'comments': 'The appartment was great, it is really nice and cosy, and it is situated at a perfect location. Ana and Goncalo were very friendly, they were very helpfull during our stay. We had a great time during our stay in Porto!',
   'date': datetime.datetime(2016, 10, 16, 4, 0),
   'listing_id': '10006546',
   'reviewer_id': '24960918',
   'reviewer_name': 'Hanneke'},
  {'_id': '111065376',
   'comments': 'Kävimme majoittajan kanssa viestinvaihtoa ennen lomaa ja he antoivat mukavan vaikutelman. He olivatkin hyvin mukavia ihmisiä. He tulivat lentokentälle vastaan kahdella autolla mikä oli hyvin ystävällistä. He kertoivat myös kaupungista ja sen nähtävyyksistä. Asunnon sijainti oli täydellinen. Se oli myös erittäin romanttinen ja kaunis. Kokemus oli hyvin onnistunut.',
   'date': datetime.datetime(2016, 10, 30, 4, 0),
   'listing_id': '10006546',
   'reviewer_id': '74079092',
   'reviewer_name': 'Kati'},
  {'_id': '111655209',
   'comments': 'Hemos pasado unos días increíbles en Oporto. Llegamos más tarde de lo que habíamos pensado y Ana & Gonçalo nos esperaron pacientemente y nos facilitaron la llegada, además nos recibieron con un regalo de bienvenida!. Nos dieron todo tipo de indicaciones y consejos más que de sobra para disfrutar de los días que estuvimos allí. La ubicación de la casa es inmejorable!! la única pega fue que el soporte de la ducha estaba roto pero como eran pocos días no quisimos molestar a Ana & Gonçalo y no se lo comentamos. ',
   'date': datetime.datetime(2016, 11, 1, 4, 0),
   'listing_id': '10006546',
   'reviewer_id': '40413493',
   'reviewer_name': 'Julia'},
  {'_id': '132811625',
   'comments': 'Great location, comfortable place, responsive and friendly host! Highly recommended!',
   'date': datetime.datetime(2017, 2, 19, 5, 0),
   'listing_id': '10006546',
   'reviewer_id': '8986056',
   'reviewer_name': 'Joshua'},
  {'_id': '144627907',
   'comments': 'This house is in the heart of Porto, set back enough to be away from the hustle and bustle but only a few steps up from the river, bars and restaurants. A great place to stay.\nThe house was clean and functional. Ana and Goncalo are perfect hosts with lots of information on places to visit and   eat.',
   'date': datetime.datetime(2017, 4, 16, 4, 0),
   'listing_id': '10006546',
   'reviewer_id': '113254568',
   'reviewer_name': 'Tracey'},
  {'_id': '149009243',
   'comments': 'The location of the house is wonderful! You are in the heart of the old city and the Douro ist just a few meters away. Perfect for a first visit to Porto!\nVery cosy and warm house with everything you need.\nGonçalo gives a lot of good tips that will help you to have a perfect stay. Communication is very easy with him.',
   'date': datetime.datetime(2017, 5, 2, 4, 0),
   'listing_id': '10006546',
   'reviewer_id': '11263097',
   'reviewer_name': 'Willem'},
  {'_id': '150518693',
   'comments': 'We spend a really good time in Porto, the flat is so well situated. The bridge is just next door, the view on the river is amazing, and plenty of restaurants and pubs, transport are just around.\nGonzalo is very kind to wait for us, also lat, for the check in, thank you.\n',
   'date': datetime.datetime(2017, 5, 8, 4, 0),
   'listing_id': '10006546',
   'reviewer_id': '108507776',
   'reviewer_name': 'Fanny'},
  {'_id': '155913947',
   'comments': 'Thanks for a great stay! 6 of us were in Porto for a long weekend and we had a blast. The apartment was perfect; location and size to accomodate us. The hosts were great, then even picked us up at the airport (for a fee but it was a great service). Thanks again! Bridget.',
   'date': datetime.datetime(2017, 5, 29, 4, 0),
   'listing_id': '10006546',
   'reviewer_id': '30254816',
   'reviewer_name': 'Bridget'},
  {'_id': '159692160',
   'comments': 'Superb location and very nice, big and overall pleasant apartment!',
   'date': datetime.datetime(2017, 6, 11, 4, 0),
   'listing_id': '10006546',
   'reviewer_id': '124514204',
   'reviewer_name': 'Oscar'},
  {'_id': '164881958',
   'comments': 'The apartment provides basic facilities but is good value for money and very well positioned for easy access to restaurants and bars, the Ribeira district and the Port house in Gaia.',
   'date': datetime.datetime(2017, 6, 29, 4, 0),
   'listing_id': '10006546',
   'reviewer_id': '105188418',
   'reviewer_name': 'Steve'},
  {'_id': '166990342',
   'comments': "Ana und Gonçalo sind sehr hilfsbereite liebe Leute, die  alles tun, damit man sich wohl fühlt. Wenn es etwas zu beanstanden gab, wird das sofort problemlos erledigt. Das Apartment ist charmant, die Möbel schon etwas mitgenommen, aber das passt insgesamt ins Bild von Porto und macht den Reiz aus. Die Lage ist super, genau am Duoro. Es gibt Strassenmusik bis in den späten Abend und auch morgens geht's früh los mit fröhlichen Lärm von der Flusspromenade. Nichts also für Leute, die es ruhig brauchen! Die Lage ist wirklich exklusiv und tröstet über den recht teuren Mietpreis. Im Umfeld gibt es typische Touri-Fallen, wo alles doppelt kostet, aber gleichzeitig findet man auch sehr nette kleine Bars, in der man chillig und günstig frühstücken oder generell lecker essen kann. Die Stadt ist klein genug, um sich schnell zurechtzufinden und groß genug, um immer wieder neues zu entdecken. Wir waren zu dritt (50, 25, 20 Jahre) und haben die Zeit wirklich genossen. ",
   'date': datetime.datetime(2017, 7, 5, 4, 0),
   'listing_id': '10006546',
   'reviewer_id': '52660694',
   'reviewer_name': 'Tina'},
  {'_id': '180030365',
   'comments': 'Very well located appartement ideal for a family of 5 who want to make the most of the city center.\nIt may be a bit noisy at night but this is acceptable.\nGlobally we recommend this place.',
   'date': datetime.datetime(2017, 8, 9, 4, 0),
   'listing_id': '10006546',
   'reviewer_id': '25469637',
   'reviewer_name': 'Mathieu'},
  {'_id': '198679769',
   'comments': 'Great location! The apartment is somewhat basic. We were family with 3 teenagers and had a good time. Also it’s a bit noisy until very late at night.',
   'date': datetime.datetime(2017, 9, 30, 4, 0),
   'listing_id': '10006546',
   'reviewer_id': '21837853',
   'reviewer_name': 'Ido'},
  {'_id': '199885226',
   'comments': 'This apartment is in the perfect location for being in the middle of the action. There were tons of restaurants close to the apartment and it was a quick walk across the bridge to tour the Port wineries. Be forewarned; if you are looking for a very quiet location, this area may not be for you. However, if you are looking to step outside of your door and start enjoying what Porto has to offer, I recommend this location.',
   'date': datetime.datetime(2017, 10, 3, 4, 0),
   'listing_id': '10006546',
   'reviewer_id': '56528632',
   'reviewer_name': 'Amanda'},
  {'_id': '207942636',
   'comments': 'Acceuil très très chaleureux de Gonçalo  et Ana lors de notre arrivée très tardive due à un changement d"\'horaire d\'avion....appartement super bien situé dans Porto près du Douro, fidèle aux photos mises sur le site....Nous avons adoré ce quartier bien animé  .....Encore merci à Gonçalo et Ana. ....',
   'date': datetime.datetime(2017, 10, 30, 4, 0),
   'listing_id': '10006546',
   'reviewer_id': '102474818',
   'reviewer_name': 'Geneviève'},
  {'_id': '209455775',
   'comments': 'Localização perfeita, muito aconchegante, Ana e Gonçalo são pessoas muito atenciosas e simpáticas!',
   'date': datetime.datetime(2017, 11, 5, 4, 0),
   'listing_id': '10006546',
   'reviewer_id': '10371877',
   'reviewer_name': 'Andrea'},
  {'_id': '223995518',
   'comments': "Perfect position to see everything that Porto has to offer. Ana and Gonçalo were great hosts quick to respond and welcoming. Couldn't recommend a better place to stay in Porto to be able to see the sights and be within walking distance to so many restaurants.",
   'date': datetime.datetime(2018, 1, 2, 5, 0),
   'listing_id': '10006546',
   'reviewer_id': '10184070',
   'reviewer_name': 'Jennifer'},
  {'_id': '225725834',
   'comments': 'Great location!',
   'date': datetime.datetime(2018, 1, 7, 5, 0),
   'listing_id': '10006546',
   'reviewer_id': '156411765',
   'reviewer_name': 'Nathalie'},
  {'_id': '230559180',

In [ ]:
df1 = pd.DataFrame(list(db.listingsAndReviews.find()))
df1.head(2)

,_id,listing_url,name,summary,space,description,neighborhood_overview,notes,transit,access,...,guests_included,images,host,address,availability,review_scores,reviews,weekly_price,monthly_price,reviews_per_month
0,10006546,https://www.airbnb.com/rooms/10006546,Ribeira Charming Duplex,Fantastic duplex apartment with three bedrooms...,Privileged views of the Douro River and Ribeir...,Fantastic duplex apartment with three bedrooms...,"In the neighborhood of the river, you can find...",Lose yourself in the narrow streets and stairc...,Transport: • Metro station and S. Bento railwa...,We are always available to help guests. The ho...,...,6,"{'thumbnail_url': '', 'medium_url': '', 'pictu...","{'host_id': '51399391', 'host_url': 'https://w...","{'street': 'Porto, Porto, Portugal', 'suburb':...","{'availability_30': 28, 'availability_60': 47,...","{'review_scores_accuracy': 9, 'review_scores_c...","[{'_id': '58663741', 'date': 2016-01-03 05:00:...",NaN,NaN,NaN
1,10021707,https://www.airbnb.com/rooms/10021707,Private Room in Bushwick,Here exists a very cozy room for rent in a sha...,,Here exists a very cozy room for rent in a sha...,,,,,...,1,"{'thumbnail_url': '', 'medium_url': '', 'pictu...","{'host_id': '11275734', 'host_url': 'https://w...","{'street': 'Brooklyn, NY, United States', 'sub...","{'availability_30': 0, 'availability_60': 0, '...","{'review_scores_accuracy': 10, 'review_scores_...","[{'_id': '61050713', 'date': 2016-01-31 05:00:...",NaN,NaN,NaN

Estrarre dalla collection le informazioni richieste:

In [ ]:
# gli appartamenti che costano più di 100 $ a notte
ris = db.listingsAndReviews.find({"property_type": "Apartment", "price": {'$gt': 100}}, {"name": 1, "property_type": 1, "price": 1})
df2 = pd.DataFrame(list(ris))
df2

,_id,name,property_type,price
0,757385,One bedroom apartment in Istanbul,Apartment,485.00
1,815654,Fabulous & Spacious Bondi Beach pad,Apartment,195.00
2,13530122,Chic City Pad with Leafy Outlook,Apartment,119.00
3,14434534,"Luxurious, bright, spacious Plaza Catalunya",Apartment,200.00
4,18082902,Bright studio apartment close to Sydney Uni!,Apartment,125.00
...,...,...,...,...
1970,27569464,Great Building Compleks and Relax Location,Apartment,105.00
1971,20822448,Mixed Dorm Bed#8 in Wan Chai (灣仔)(混合床位)(一張床位),Apartment,283.00
1972,8144456,市中心特色唐樓 Downtown Guesthouse,Apartment,251.00
1973,30810129,Dorm 3baths SohoEast..,Apartment,251.00
1974,31095245,Dorm 3baths SohoEast......,Apartment,251.00

In [ ]:
# gli appartamenti che costano tra i 100 $ e i 200 $ a notte
ris = db.listingsAndReviews.find({"property_type": "Apartment", "price": {'$gt': 100, '$lt': 200 }}, {"name": 1, "property_type": 1, "price": 1})
df2 = pd.DataFrame(list(ris))
df2

,_id,name,property_type,price
0,815654,Fabulous & Spacious Bondi Beach pad,Apartment,195.00
1,13530122,Chic City Pad with Leafy Outlook,Apartment,119.00
2,18082902,Bright studio apartment close to Sydney Uni!,Apartment,125.00
3,2151479,Newly renovated house,Apartment,125.00
4,23357535,Sydney City Elegance & Pool.,Apartment,148.00
...,...,...,...,...
815,31806673,Causeway Bay Room(C1b),Apartment,188.00
816,31764157,Sheung Wan Room in Flat Share(Sw21e),Apartment,173.00
817,30049654,The boys' room (don't book before inquiry),Apartment,149.00
818,30096786,ÖRNEK ORGANİSATİON Touristendienst,Apartment,111.00
819,27569464,Great Building Compleks and Relax Location,Apartment,105.00

In [ ]:
# gli appartamenti che hanno almeno 5 posti letto e che costano tra i 50 $ e 100 $ a notte
ris = db.listingsAndReviews.find({"property_type": "Apartment", "beds": {'$gt': 5}, "price": {'$gt': 50, '$lt': 100 }}, {"name": 1, "beds": 1, "price": 1, "property_type": 1, "_id": 0})
df2 = pd.DataFrame(list(ris))
df2

                                             name property_type  beds  price
0                    MONTJUIC FOUNTAINS APARTMENT     Apartment     6  85.00
1               The Porto Concierge - Baron Omega     Apartment     6  75.00
2                        Gracia 3 BR 2 BA Terrace     Apartment     6  62.00
3   Apartemento centro porto casa da musica 90 m2     Apartment     6  71.00
4                                   Tucson Suites     Apartment     6  85.00
5             Wow Historical Brooklyn New York!@!     Apartment     6  97.00
6                                    Lulapartment     Apartment     6  56.00
7              Stone House 2, com terraço e Wi-Fi     Apartment     7  85.00
8            CALABRIA, central, large, 4 bedrooms     Apartment     7  92.00
9                         BCN Duplex Mirò Monthly     Apartment     7  89.00
10                          Pin Porto City Center     Apartment     9  90.00

In [ ]:
# gli appartamenti in Portogallo
ris = db.listingsAndReviews.find({"property_type": "Apartment",  "address.country": "Portugal"}, {"name": 1, "property_type": 1, "address": 1})
df2 = pd.DataFrame(list(ris))
df2

,_id,name,property_type,address
0,10117617,A Casa Alegre é um apartamento T1.,Apartment,"{'street': 'Vila do Conde, Porto, Portugal', '..."
1,10269320,FloresRooms 3T,Apartment,"{'street': 'Porto, Porto, Portugal', 'suburb':..."
2,10560325,Spacious and well located apartment,Apartment,"{'street': 'Porto, Porto, Portugal', 'suburb':..."
3,1036027,BBC OPORTO 4X2,Apartment,"{'street': 'Porto, Porto District, Portugal', ..."
4,10487917,Heroísmo IV,Apartment,"{'street': 'Porto, Porto, Portugal', 'suburb':..."
...,...,...,...,...
378,901441,Go2oporto @Ribeira do Porto 1,Apartment,"{'street': 'Porto, Porto, Portugal', 'suburb':..."
379,9983221,Cozy apartment downtown Porto,Apartment,"{'street': 'Porto, Porto, Portugal', 'suburb':..."
380,9379065,Soares Guest House,Apartment,"{'street': 'Porto, Porto, Portugal', 'suburb':..."
381,9969335,"Central, Modern, University, Metro",Apartment,"{'street': 'Porto, Porto, Portugal', 'suburb':..."
382,9917859,StayIN Oporto Música - Apartment,Apartment,"{'street': 'Porto, Porto, Portugal', 'suburb':..."

In [ ]:
# gli appartamenti che non si trovano in Portogallo e in Spagna
ris = db.listingsAndReviews.find({"property_type": "Apartment",  "address.country": {'$not': {'$in': ["Portugal", "Spain"]}}}, {"name": 1, "property_type": 1, "address": 1})
df2 = pd.DataFrame(list(ris))
df2

,_id,name,property_type,address
0,757385,One bedroom apartment in Istanbul,Apartment,"{'street': 'Istanbul, Istanbul, Turkey', 'subu..."
1,815654,Fabulous & Spacious Bondi Beach pad,Apartment,"{'street': 'Bondi Beach, NSW, Australia', 'sub..."
2,13530122,Chic City Pad with Leafy Outlook,Apartment,"{'street': 'Elizabeth Bay, NSW, Australia', 's..."
3,18082902,Bright studio apartment close to Sydney Uni!,Apartment,"{'street': 'Forest Lodge, NSW, Australia', 'su..."
4,21199380,1 bedroom VIP apartment near Bell Center - 501,Apartment,"{'street': 'Montréal, Québec, Canada', 'suburb..."
...,...,...,...,...
2704,19865325,Vaga em apartamento conjugado(LEIAM A DESCRIÇÃ...,Apartment,"{'street': 'Copacabana, Rio de Janeiro, Brazil..."
2705,20822448,Mixed Dorm Bed#8 in Wan Chai (灣仔)(混合床位)(一張床位),Apartment,"{'street': 'Hong Kong, Hong Kong Island, Hong ..."
2706,8144456,市中心特色唐樓 Downtown Guesthouse,Apartment,"{'street': 'Hong Kong, Kowloon, Hong Kong', 's..."
2707,30810129,Dorm 3baths SohoEast..,Apartment,"{'street': 'Hong Kong, Hong Kong Island, Hong ..."
2708,31095245,Dorm 3baths SohoEast......,Apartment,"{'street': 'Hong Kong, Hong Kong Island, Hong ..."

In [ ]:
# gli appartamenti negli Stati Uniti che hanno il wifi
# ordinare in ordine decrescente sul prezzo per notte e prendere solo i primi 10 appartamenti
ris = db.listingsAndReviews.find({"property_type": "Apartment",  '$and': [{"address.country": "United States"}, {"amenities": "Wifi"}]}, {"name": 1, "property_type": 1, "address": 1, "amenities": 1, "price": 1, "_id": 0}).sort([("price", -1)])
df2 = pd.DataFrame(list(ris))
df2.head(10)

,name,property_type,amenities,price,address
0,Luxury Chelsea Townhouse at the High Line,Apartment,"[TV, Cable TV, Wifi, Air conditioning, Kitchen...",725.00,"{'street': 'New York, NY, United States', 'sub..."
1,Large Garden Duplex on Park block,Apartment,"[TV, Cable TV, Wifi, Air conditioning, Kitchen...",560.00,"{'street': 'New York, NY, United States', 'sub..."
2,"Chelsea NYC luxury 2 bed/2 bath, garden apt",Apartment,"[TV, Cable TV, Wifi, Air conditioning, Kitchen...",555.00,"{'street': 'New York, NY, United States', 'sub..."
3,Gorgeous Designer Decorated 2BR Loft,Apartment,"[TV, Wifi, Air conditioning, Kitchen, Buzzer/w...",550.00,"{'street': 'Brooklyn, NY, United States', 'sub..."
4,Most breathtaking view of Manhattan,Apartment,"[TV, Cable TV, Internet, Wifi, Air conditionin...",500.00,"{'street': 'Brooklyn, NY, United States', 'sub..."
5,Large duplex West Village apartment,Apartment,"[TV, Cable TV, Internet, Wifi, Air conditionin...",500.00,"{'street': 'New York, NY, United States', 'sub..."
6,Beautiful Apartment Hells Kitchen,Apartment,"[TV, Cable TV, Internet, Wifi, Air conditionin...",450.00,"{'street': 'New York, NY, United States', 'sub..."
7,3 Bedroom / Ocean views / Free Parking - Waikiki,Apartment,"[TV, Cable TV, Internet, Wifi, Air conditionin...",449.00,"{'street': 'Honolulu, HI, United States', 'sub..."
8,Duplex apartment with garden,Apartment,"[TV, Cable TV, Internet, Wifi, Air conditionin...",439.00,"{'street': 'New York, NY, United States', 'sub..."
9,Elegant 2BD in Time Sq with W/D!,Apartment,"[TV, Internet, Wifi, Air conditioning, Wheelch...",429.00,"{'street': 'New York, NY, United States', 'sub..."

In [ ]:
# il numero di appartamenti in Portogallo
result = db.listingsAndReviews.aggregate([{"$match": {"property_type": "Apartment"}},
                                          {"$match": {"address.country": "Portugal"}},
                                          {"$group": {"_id": "$address.country", "total": {"$sum": 1}}}])
df2 = pd.DataFrame(list(result))
df2

        _id  total
0  Portugal    383

In [ ]:
# il numero di appartamenti nelle varie nazioni
result = db.listingsAndReviews.aggregate([{"$match": {"property_type": "Apartment"}},
                                          {"$group": {"_id": "$address.country", "total": {"$sum": 1}}}])
df2 = pd.DataFrame(list(result))
df2

             _id  total
0         Canada    467
1          China     10
2      Hong Kong    434
3      Australia    334
4         Brazil    455
5  United States    596
6          Spain    534
7         Turkey    413
8       Portugal    383

In [ ]:
# le nazioni con più di 600 appartamenti
result = db.listingsAndReviews.aggregate([{"$match": {"property_type": "Apartment"}},
                                          {"$group" : {"_id": "$address.country", "total": {"$sum": 1}}},
                                          {"$match": {"total": {"$gt": 500 }}}])
df2 = pd.DataFrame(list(result))
df2

             _id  total
0          Spain    534
1  United States    596

In [ ]:
# gli appartamenti che hanno la parola 'beach' nella descrizione
result = db.listingsAndReviews.aggregate([
                                          {"$match": {"description": {"$regex" : "beach"}}}])
df11 = pd.DataFrame(list(result))
df11[["description"]]

                                           description
0    The Apartment has a living room, toilet, bedro...
1    Great studio apartment freshly painted and dec...
2    Room 2  Private room in charming recently reno...
3    The place to be on the north shore is where yo...
4    This spacious, light filled studio has everyth...
..                                                 ...
948  Beautiful modern architect designed home - 4 b...
949  Our apartment is in the best spot of Leblon Tw...
950  Ideal! The apartment is located in one of the ...
951  A bright large double room is available in a b...
952  Relax Hawaiian Style in Gated Community on Oce...

[953 rows x 1 columns]